package NBADemo;
public class NBATeamLauncher {
	public static void main(String[] args) {
		NBATeam myTeam1 = new NBATeam("Cavaliers");
		NBATeam myTeam2 = new NBATeam("Spurs");
		NBATeam myTeam3 = new NBATeam("Warriors");
		NBATeam myTeam4 = new NBATeam("Thunder");
		NBATeam myTeam5 = new NBATeam("Clippers");
		NBATeam myTeam6 = new NBATeam("Heat");
		System.out.println(myTeam1.getName()+" two point: "+myTeam1.getTwoPointShooting());
		System.out.println(myTeam1.getName()+" three point: "+myTeam1.getThreePointShooting());
		System.out.println(myTeam1.getName()+" athleticism: "+myTeam1.getAthleticism());
		System.out.println(myTeam1.getName()+" REBOUND: "+myTeam1.getRebound());
		System.out.println(myTeam1.getName()+" defense: "+myTeam1.getDefense());	
		System.out.println(myTeam1.getName()+" Playmaking: "+myTeam1.getPlaymaking());
		System.out.println(myTeam1.getName()+" OverAll: "+myTeam1.getOverAll());
		System.out.println( "the one to make shot is "+myTeam1.shootingPlayer(false) );
		System.out.println();		
		System.out.println(myTeam2.getName()+" two point: "+myTeam2.getTwoPointShooting());
		System.out.println(myTeam2.getName()+" three point: "+myTeam2.getThreePointShooting());
		System.out.println(myTeam2.getName()+" athleticism: "+myTeam2.getAthleticism());
		System.out.println(myTeam2.getName()+" REBOUND: "+myTeam2.getRebound());
		System.out.println(myTeam2.getName()+" defense: "+myTeam2.getDefense());
		System.out.println(myTeam2.getName()+" Playmaking: "+myTeam2.getPlaymaking());
		System.out.println(myTeam2.getName()+" OverAll: "+myTeam2.getOverAll());
		System.out.println();
		System.out.println(myTeam3.getName()+" two point: "+myTeam3.getTwoPointShooting());
		System.out.println(myTeam3.getName()+" three point: "+myTeam3.getThreePointShooting());	
		System.out.println(myTeam3.getName()+" athleticism: "+myTeam3.getAthleticism());
		System.out.println(myTeam3.getName()+" REBOUND: "+myTeam3.getRebound());
		System.out.println(myTeam3.getName()+" defense: "+myTeam3.getDefense());
		System.out.println(myTeam3.getName()+" Playmaking: "+myTeam3.getPlaymaking());
		System.out.println(myTeam3.getName()+" OverAll: "+myTeam3.getOverAll());
		System.out.println( "the one to make shot is "+myTeam3.shootingPlayer(false) );
		System.out.println();
		System.out.println(myTeam4.getName()+" two point: "+myTeam4.getTwoPointShooting());
		System.out.println(myTeam4.getName()+" three point: "+myTeam4.getThreePointShooting());
		System.out.println(myTeam4.getName()+" athleticism: "+myTeam4.getAthleticism());
		System.out.println(myTeam4.getName()+" REBOUND: "+myTeam4.getRebound());
		System.out.println(myTeam4.getName()+" defense: "+myTeam4.getDefense());
		System.out.println(myTeam4.getName()+" Playmaking: "+myTeam4.getPlaymaking());
		System.out.println(myTeam4.getName()+" OverAll: "+myTeam4.getOverAll());
		System.out.println( "the one to make shot is "+myTeam4.shootingPlayer(false) );
		System.out.println();
		System.out.println(myTeam5.getName()+" two point: "+myTeam5.getTwoPointShooting());
		System.out.println(myTeam5.getName()+" three point: "+myTeam5.getThreePointShooting());
		System.out.println(myTeam5.getName()+" athleticism: "+myTeam5.getAthleticism());
		System.out.println(myTeam5.getName()+" REBOUND: "+myTeam5.getRebound());
		System.out.println(myTeam5.getName()+" defense: "+myTeam5.getDefense());	
		System.out.println(myTeam5.getName()+" Playmaking: "+myTeam5.getPlaymaking());
		System.out.println(myTeam5.getName()+" OverAll: "+myTeam5.getOverAll());
		System.out.println( "the one to make shot is "+myTeam5.shootingPlayer(false) );
		System.out.println();
		System.out.println(myTeam6.getName()+" two point: "+myTeam6.getTwoPointShooting());
		System.out.println(myTeam6.getName()+" three point: "+myTeam6.getThreePointShooting());
		System.out.println(myTeam6.getName()+" athleticism: "+myTeam6.getAthleticism());
		System.out.println(myTeam6.getName()+" REBOUND: "+myTeam6.getRebound());
		System.out.println(myTeam6.getName()+" defense: "+myTeam6.getDefense());	
		System.out.println(myTeam6.getName()+" Playmaking: "+myTeam6.getPlaymaking());
		System.out.println(myTeam6.getName()+" OverAll: "+myTeam6.getOverAll());
		System.out.println( "the one to make shot is "+myTeam6.shootingPlayer(false) );
		System.out.println();
	}
}
